In [1]:
import gzip
import pickle
import networkx as nx
import pandas as pd
import numpy as np
import random
import os

## Data Loading

### Writing PyG Dataset

In [2]:
import torch

/opt/anaconda3/envs/thesis/lib/python3.10/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [3]:
from torch_geometric.data import InMemoryDataset
from torch.utils.data import DataLoader

In [4]:
from torch_geometric.utils import from_networkx, to_networkx

In [5]:
def generate_feature_vector(G):
    x = torch.randn(G.number_of_nodes(), 1)
    ind = 0
    for node in G.nodes():
        x[ind][0] = G.degree[node]
        ind += 1
    return x

In [6]:
class LamanDataset(InMemoryDataset):
    def __init__(self, root, data_dir, transform=None, pre_transform=None, pre_filter=None):
        self.data_dir = data_dir
        super().__init__(root, transform, pre_transform, pre_filter)
        self.data, self.slices = torch.load(self.processed_paths[0])
        
    @property
    def processed_file_names(self):
        return ['data.pt']
        
    def process(self):
        # processing code here
        total_laman_data = None
        with gzip.open(self.data_dir, 'r') as f:
            total_laman_data = pickle.load(f)
            
        data_list = []
        ind = 0
        # convert from graph to Data object
        for graph in total_laman_data[0]:
            ind += 1
            num_nodes = nx.number_of_nodes(graph)
            x = generate_feature_vector(graph)
            graph_as_data = from_networkx(graph)
            graph_as_data.x = x
            graph_as_data.label = 0
            data_list.append(graph_as_data)
            
        ind = 0
        for graph in total_laman_data[1]:
            ind += 1
            num_nodes = nx.number_of_nodes(graph)
            x = generate_feature_vector(graph)
            graph_as_data = from_networkx(graph)
            graph_as_data.x = x
            graph_as_data.label = 1
            data_list.append(graph_as_data)
            
        data, slices = self.collate(data_list)
        torch.save((data, slices), self.processed_paths[0])

In [7]:
DATA_PATH = "data/test.pkl.gz"

In [8]:
laman_data = LamanDataset("", DATA_PATH)

## Split into Train / Test

In [9]:
from torch.utils.data import random_split

proportions = [.7, .3]
lengths = [int(p * len(laman_data)) for p in proportions]
lengths[-1] = len(laman_data) - sum(lengths[:-1])

generator1 = torch.Generator().manual_seed(42)
train_data, test_data = random_split(laman_data, lengths, generator=generator1)

In [10]:
from torch_geometric.loader import DataLoader
train_loader = DataLoader(train_data, batch_size = 128, shuffle=True)
test_loader = DataLoader(test_data, batch_size = 64, shuffle=True)

In [11]:
print("Number of train batches: ", len(train_loader))
print("Number of test batches: ", len(test_loader))

Number of train batches:  6
Number of test batches:  5


In [12]:
for data in train_loader:
    print(data)
    break

DataBatch(edge_index=[2, 44460], x=[7666, 1], label=[128], num_nodes=7666, batch=[7666], ptr=[129])


## Model Architecture & Training

In [13]:
from gin.gin_single_layer import GIN

In [14]:
model = GIN(num_features=1)
print(model)
print("Number of parameters: ", sum(p.numel() for p in model.parameters()))

GIN(
  (conv1): GINConv(nn=Sequential(
    (0): Linear(in_features=1, out_features=2, bias=True)
    (1): BatchNorm1d(2, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (2): ReLU()
    (3): Linear(in_features=2, out_features=2, bias=True)
    (4): ReLU()
  ))
  (lin1): Linear(in_features=4, out_features=4, bias=True)
  (lin2): Linear(in_features=4, out_features=1, bias=True)
)
Number of parameters:  39


In [15]:
from torch_geometric.data import DataLoader
from torch.nn import BCELoss
import warnings
warnings.filterwarnings("ignore")

loss_fn = torch.nn.BCELoss()
optimizer = torch.optim.Adam(model.parameters(),
                                      lr=0.001)

In [ ]:
# hyper-parameter tuning
# grid-search over [lr ... ] x [batch size ... ]
# look into this more

In [16]:
def train(data):
    ind = 0
    for batch in data:
        optimizer.zero_grad()
        pred, embedding = model(batch.x, batch.edge_index, batch.batch)
        pred = torch.squeeze(pred)
        loss = loss_fn(pred.float(), batch.label.float())
        loss.backward()
        optimizer.step()
        ind += 1

    return loss, None

In [17]:
def check_accuracy(model, loader):
    num_correct = 0
    num_samples = 0
    model.eval()

    with torch.no_grad():
        for batch in loader:
            pred, embedding = model(batch.x, batch.edge_index, batch.batch)
            pred = torch.squeeze(pred)
            y = batch.label
            predictions = (pred > 0.5).long() 
            num_correct += (predictions == y).sum() 
            num_samples += predictions.size(0)
                        
    return float(num_correct)/float(num_samples)*100

In [19]:
print("Starting training...")
losses = []

bestModel = None
bestAcc = 0

for epoch in range(10000):
    loss, h = train(train_loader)
    losses.append(loss)
    print(f"Epoch {epoch} | Train loss {loss}")
    train_acc, test_acc = check_accuracy(model, train_loader), check_accuracy(model, test_loader)
    
    if test_acc > bestAcc:
        bestAcc = test_acc
        bestModel = model 
        
    print(f"Train Accuracy {train_acc} | Test Accuracy {test_acc}")
    

Starting training...
Epoch 0 | Train loss 0.6735578179359436
Train Accuracy 52.714285714285715 | Test Accuracy 49.0
Epoch 1 | Train loss 0.6514549255371094
Train Accuracy 53.28571428571428 | Test Accuracy 50.33333333333333
Epoch 2 | Train loss 0.6459006071090698
Train Accuracy 53.42857142857142 | Test Accuracy 50.66666666666667
Epoch 3 | Train loss 0.6609451174736023
Train Accuracy 52.85714285714286 | Test Accuracy 49.0
Epoch 4 | Train loss 0.6766197085380554
Train Accuracy 53.142857142857146 | Test Accuracy 49.333333333333336
Epoch 5 | Train loss 0.6739117503166199
Train Accuracy 53.42857142857142 | Test Accuracy 51.0
Epoch 6 | Train loss 0.6409355998039246
Train Accuracy 53.42857142857142 | Test Accuracy 51.0
Epoch 7 | Train loss 0.6664978265762329
Train Accuracy 53.42857142857142 | Test Accuracy 51.0
Epoch 8 | Train loss 0.6729203462600708
Train Accuracy 53.57142857142857 | Test Accuracy 51.33333333333333
Epoch 9 | Train loss 0.6748982667922974
Train Accuracy 54.85714285714286 | Tes

Epoch 80 | Train loss 0.5377725958824158
Train Accuracy 78.71428571428571 | Test Accuracy 77.66666666666666
Epoch 81 | Train loss 0.5837600231170654
Train Accuracy 79.0 | Test Accuracy 77.0
Epoch 82 | Train loss 0.5396813750267029
Train Accuracy 76.14285714285714 | Test Accuracy 75.33333333333333
Epoch 83 | Train loss 0.5760940909385681
Train Accuracy 73.71428571428571 | Test Accuracy 70.66666666666667
Epoch 84 | Train loss 0.5466896891593933
Train Accuracy 79.0 | Test Accuracy 77.33333333333333
Epoch 85 | Train loss 0.5641297698020935
Train Accuracy 76.57142857142857 | Test Accuracy 75.33333333333333
Epoch 86 | Train loss 0.5665005445480347
Train Accuracy 78.57142857142857 | Test Accuracy 76.66666666666667
Epoch 87 | Train loss 0.523554801940918
Train Accuracy 79.14285714285715 | Test Accuracy 77.33333333333333
Epoch 88 | Train loss 0.5695174336433411
Train Accuracy 76.57142857142857 | Test Accuracy 75.33333333333333
Epoch 89 | Train loss 0.5052729845046997
Train Accuracy 80.428571428

Epoch 161 | Train loss 0.44026753306388855
Train Accuracy 88.0 | Test Accuracy 88.33333333333333
Epoch 162 | Train loss 0.44752705097198486
Train Accuracy 88.0 | Test Accuracy 88.0
Epoch 163 | Train loss 0.40444907546043396
Train Accuracy 88.42857142857142 | Test Accuracy 89.0
Epoch 164 | Train loss 0.3731503188610077
Train Accuracy 87.71428571428571 | Test Accuracy 87.33333333333333
Epoch 165 | Train loss 0.374904602766037
Train Accuracy 88.28571428571429 | Test Accuracy 88.33333333333333
Epoch 166 | Train loss 0.4185776710510254
Train Accuracy 88.14285714285714 | Test Accuracy 88.33333333333333
Epoch 167 | Train loss 0.3660051226615906
Train Accuracy 87.42857142857143 | Test Accuracy 87.0
Epoch 168 | Train loss 0.42889100313186646
Train Accuracy 89.42857142857143 | Test Accuracy 91.0
Epoch 169 | Train loss 0.35877150297164917
Train Accuracy 87.28571428571429 | Test Accuracy 87.0
Epoch 170 | Train loss 0.44269195199012756
Train Accuracy 89.57142857142857 | Test Accuracy 90.66666666666

Train Accuracy 89.57142857142857 | Test Accuracy 91.0
Epoch 241 | Train loss 0.32283493876457214
Train Accuracy 88.85714285714286 | Test Accuracy 90.66666666666666
Epoch 242 | Train loss 0.353786438703537
Train Accuracy 89.42857142857143 | Test Accuracy 90.66666666666666
Epoch 243 | Train loss 0.3336390256881714
Train Accuracy 89.42857142857143 | Test Accuracy 91.0
Epoch 244 | Train loss 0.2972354292869568
Train Accuracy 89.14285714285714 | Test Accuracy 91.0
Epoch 245 | Train loss 0.26026687026023865
Train Accuracy 89.57142857142857 | Test Accuracy 91.66666666666666
Epoch 246 | Train loss 0.3187680244445801
Train Accuracy 89.14285714285714 | Test Accuracy 91.0
Epoch 247 | Train loss 0.22473078966140747
Train Accuracy 89.28571428571429 | Test Accuracy 91.0
Epoch 248 | Train loss 0.28049689531326294
Train Accuracy 89.57142857142857 | Test Accuracy 91.33333333333333
Epoch 249 | Train loss 0.3207854926586151
Train Accuracy 89.28571428571429 | Test Accuracy 91.0
Epoch 250 | Train loss 0.27

Epoch 320 | Train loss 0.1900477558374405
Train Accuracy 88.85714285714286 | Test Accuracy 91.0
Epoch 321 | Train loss 0.2234320342540741
Train Accuracy 89.14285714285714 | Test Accuracy 93.33333333333333
Epoch 322 | Train loss 0.1983860433101654
Train Accuracy 89.0 | Test Accuracy 90.33333333333333
Epoch 323 | Train loss 0.32872307300567627
Train Accuracy 89.0 | Test Accuracy 93.0
Epoch 324 | Train loss 0.2726336419582367
Train Accuracy 89.0 | Test Accuracy 90.66666666666666
Epoch 325 | Train loss 0.2999151647090912
Train Accuracy 89.42857142857143 | Test Accuracy 93.33333333333333
Epoch 326 | Train loss 0.2765190303325653
Train Accuracy 89.0 | Test Accuracy 91.66666666666666
Epoch 327 | Train loss 0.2938734292984009
Train Accuracy 89.0 | Test Accuracy 93.0
Epoch 328 | Train loss 0.3277543783187866
Train Accuracy 88.71428571428571 | Test Accuracy 90.66666666666666
Epoch 329 | Train loss 0.32947152853012085
Train Accuracy 89.14285714285714 | Test Accuracy 93.33333333333333
Epoch 330 | 

Train Accuracy 89.14285714285714 | Test Accuracy 93.0
Epoch 402 | Train loss 0.23390360176563263
Train Accuracy 89.57142857142857 | Test Accuracy 92.0
Epoch 403 | Train loss 0.29045379161834717
Train Accuracy 89.42857142857143 | Test Accuracy 92.0
Epoch 404 | Train loss 0.17737694084644318
Train Accuracy 89.0 | Test Accuracy 91.0
Epoch 405 | Train loss 0.31877657771110535
Train Accuracy 89.14285714285714 | Test Accuracy 93.33333333333333
Epoch 406 | Train loss 0.385846883058548
Train Accuracy 89.42857142857143 | Test Accuracy 91.66666666666666
Epoch 407 | Train loss 0.32718631625175476
Train Accuracy 89.0 | Test Accuracy 92.66666666666666
Epoch 408 | Train loss 0.24526628851890564
Train Accuracy 89.28571428571429 | Test Accuracy 93.33333333333333
Epoch 409 | Train loss 0.33765193819999695
Train Accuracy 88.28571428571429 | Test Accuracy 90.66666666666666
Epoch 410 | Train loss 0.37993142008781433
Train Accuracy 88.71428571428571 | Test Accuracy 93.33333333333333
Epoch 411 | Train loss 

Train Accuracy 89.14285714285714 | Test Accuracy 91.66666666666666
Epoch 481 | Train loss 0.37629038095474243
Train Accuracy 89.14285714285714 | Test Accuracy 93.0
Epoch 482 | Train loss 0.1670231968164444
Train Accuracy 89.14285714285714 | Test Accuracy 91.66666666666666
Epoch 483 | Train loss 0.1625082939863205
Train Accuracy 89.14285714285714 | Test Accuracy 93.0
Epoch 484 | Train loss 0.16054721176624298
Train Accuracy 89.14285714285714 | Test Accuracy 91.66666666666666
Epoch 485 | Train loss 0.1895885169506073
Train Accuracy 89.42857142857143 | Test Accuracy 93.33333333333333
Epoch 486 | Train loss 0.24400025606155396
Train Accuracy 89.42857142857143 | Test Accuracy 91.66666666666666
Epoch 487 | Train loss 0.26390302181243896
Train Accuracy 89.14285714285714 | Test Accuracy 93.0
Epoch 488 | Train loss 0.1711857169866562
Train Accuracy 89.14285714285714 | Test Accuracy 91.66666666666666
Epoch 489 | Train loss 0.33763474225997925
Train Accuracy 89.28571428571429 | Test Accuracy 93.0

Epoch 561 | Train loss 0.1642341911792755
Train Accuracy 89.28571428571429 | Test Accuracy 93.0
Epoch 562 | Train loss 0.228929802775383
Train Accuracy 89.28571428571429 | Test Accuracy 91.66666666666666
Epoch 563 | Train loss 0.4055555760860443
Train Accuracy 89.14285714285714 | Test Accuracy 93.0
Epoch 564 | Train loss 0.30555111169815063
Train Accuracy 89.28571428571429 | Test Accuracy 93.33333333333333
Epoch 565 | Train loss 0.24690355360507965
Train Accuracy 89.0 | Test Accuracy 90.66666666666666
Epoch 566 | Train loss 0.16791753470897675
Train Accuracy 89.14285714285714 | Test Accuracy 93.0
Epoch 567 | Train loss 0.33473703265190125
Train Accuracy 89.28571428571429 | Test Accuracy 94.0
Epoch 568 | Train loss 0.29428786039352417
Train Accuracy 89.14285714285714 | Test Accuracy 91.66666666666666
Epoch 569 | Train loss 0.19063185155391693
Train Accuracy 89.14285714285714 | Test Accuracy 93.0
Epoch 570 | Train loss 0.27562758326530457
Train Accuracy 89.28571428571429 | Test Accuracy 

Train Accuracy 89.14285714285714 | Test Accuracy 93.0
Epoch 644 | Train loss 0.23743213713169098
Train Accuracy 89.42857142857143 | Test Accuracy 91.66666666666666
Epoch 645 | Train loss 0.3362961709499359
Train Accuracy 89.14285714285714 | Test Accuracy 93.0
Epoch 646 | Train loss 0.23822085559368134
Train Accuracy 89.14285714285714 | Test Accuracy 93.0
Epoch 647 | Train loss 0.25791555643081665
Train Accuracy 89.28571428571429 | Test Accuracy 93.0
Epoch 648 | Train loss 0.2523392140865326
Train Accuracy 89.28571428571429 | Test Accuracy 91.66666666666666
Epoch 649 | Train loss 0.13002164661884308
Train Accuracy 89.28571428571429 | Test Accuracy 91.66666666666666
Epoch 650 | Train loss 0.33333876729011536
Train Accuracy 89.14285714285714 | Test Accuracy 93.0
Epoch 651 | Train loss 0.29149600863456726
Train Accuracy 89.14285714285714 | Test Accuracy 93.0
Epoch 652 | Train loss 0.21277612447738647
Train Accuracy 89.28571428571429 | Test Accuracy 91.66666666666666
Epoch 653 | Train loss 

Train Accuracy 89.28571428571429 | Test Accuracy 91.66666666666666
Epoch 726 | Train loss 0.27286237478256226
Train Accuracy 89.0 | Test Accuracy 93.0
Epoch 727 | Train loss 0.20788849890232086
Train Accuracy 89.0 | Test Accuracy 93.0
Epoch 728 | Train loss 0.2644931674003601
Train Accuracy 89.14285714285714 | Test Accuracy 93.0
Epoch 729 | Train loss 0.23461848497390747
Train Accuracy 89.42857142857143 | Test Accuracy 92.0
Epoch 730 | Train loss 0.22099372744560242
Train Accuracy 89.14285714285714 | Test Accuracy 92.66666666666666
Epoch 731 | Train loss 0.2075781524181366
Train Accuracy 89.14285714285714 | Test Accuracy 93.66666666666667
Epoch 732 | Train loss 0.33253195881843567
Train Accuracy 89.14285714285714 | Test Accuracy 91.33333333333333
Epoch 733 | Train loss 0.2694602310657501
Train Accuracy 89.14285714285714 | Test Accuracy 93.33333333333333
Epoch 734 | Train loss 0.21985241770744324
Train Accuracy 89.28571428571429 | Test Accuracy 91.66666666666666
Epoch 735 | Train loss 0

Train Accuracy 89.28571428571429 | Test Accuracy 91.66666666666666
Epoch 806 | Train loss 0.31505540013313293
Train Accuracy 89.28571428571429 | Test Accuracy 94.0
Epoch 807 | Train loss 0.23512084782123566
Train Accuracy 88.57142857142857 | Test Accuracy 91.0
Epoch 808 | Train loss 0.1053379699587822
Train Accuracy 88.71428571428571 | Test Accuracy 93.33333333333333
Epoch 809 | Train loss 0.23484447598457336
Train Accuracy 89.14285714285714 | Test Accuracy 92.33333333333333
Epoch 810 | Train loss 0.22185221314430237
Train Accuracy 89.0 | Test Accuracy 91.33333333333333
Epoch 811 | Train loss 0.41390737891197205
Train Accuracy 89.0 | Test Accuracy 93.0
Epoch 812 | Train loss 0.3263609707355499
Train Accuracy 89.14285714285714 | Test Accuracy 93.33333333333333
Epoch 813 | Train loss 0.3338046371936798
Train Accuracy 89.0 | Test Accuracy 91.33333333333333
Epoch 814 | Train loss 0.2875482141971588
Train Accuracy 89.0 | Test Accuracy 93.33333333333333
Epoch 815 | Train loss 0.2675952017307

Train Accuracy 89.14285714285714 | Test Accuracy 92.33333333333333
Epoch 887 | Train loss 0.20488402247428894
Train Accuracy 89.28571428571429 | Test Accuracy 93.0
Epoch 888 | Train loss 0.4040273427963257
Train Accuracy 89.14285714285714 | Test Accuracy 94.0
Epoch 889 | Train loss 0.23995932936668396
Train Accuracy 88.57142857142857 | Test Accuracy 91.0
Epoch 890 | Train loss 0.3635120987892151
Train Accuracy 89.28571428571429 | Test Accuracy 93.0
Epoch 891 | Train loss 0.19027765095233917
Train Accuracy 89.28571428571429 | Test Accuracy 93.0
Epoch 892 | Train loss 0.26872342824935913
Train Accuracy 89.28571428571429 | Test Accuracy 92.33333333333333
Epoch 893 | Train loss 0.24864599108695984
Train Accuracy 89.28571428571429 | Test Accuracy 93.0
Epoch 894 | Train loss 0.3300527036190033
Train Accuracy 89.28571428571429 | Test Accuracy 91.33333333333333
Epoch 895 | Train loss 0.23357780277729034
Train Accuracy 89.14285714285714 | Test Accuracy 93.66666666666667
Epoch 896 | Train loss 0

Train Accuracy 89.57142857142857 | Test Accuracy 92.33333333333333
Epoch 969 | Train loss 0.17075657844543457
Train Accuracy 89.14285714285714 | Test Accuracy 92.66666666666666
Epoch 970 | Train loss 0.3594067692756653
Train Accuracy 89.28571428571429 | Test Accuracy 91.33333333333333
Epoch 971 | Train loss 0.17653995752334595
Train Accuracy 89.28571428571429 | Test Accuracy 92.66666666666666
Epoch 972 | Train loss 0.3395656645298004
Train Accuracy 89.28571428571429 | Test Accuracy 94.0
Epoch 973 | Train loss 0.23938356339931488
Train Accuracy 89.28571428571429 | Test Accuracy 91.33333333333333
Epoch 974 | Train loss 0.21209894120693207
Train Accuracy 89.28571428571429 | Test Accuracy 92.66666666666666
Epoch 975 | Train loss 0.16365092992782593
Train Accuracy 89.28571428571429 | Test Accuracy 92.33333333333333
Epoch 976 | Train loss 0.2857765257358551
Train Accuracy 89.57142857142857 | Test Accuracy 91.66666666666666
Epoch 977 | Train loss 0.22019927203655243
Train Accuracy 89.14285714

Train Accuracy 89.14285714285714 | Test Accuracy 92.66666666666666
Epoch 1051 | Train loss 0.24053475260734558
Train Accuracy 89.14285714285714 | Test Accuracy 93.0
Epoch 1052 | Train loss 0.2654285728931427
Train Accuracy 89.42857142857143 | Test Accuracy 92.33333333333333
Epoch 1053 | Train loss 0.23155753314495087
Train Accuracy 89.14285714285714 | Test Accuracy 92.33333333333333
Epoch 1054 | Train loss 0.363312691450119
Train Accuracy 89.28571428571429 | Test Accuracy 92.33333333333333
Epoch 1055 | Train loss 0.18911199271678925
Train Accuracy 89.28571428571429 | Test Accuracy 92.33333333333333
Epoch 1056 | Train loss 0.3775061368942261
Train Accuracy 89.14285714285714 | Test Accuracy 93.0
Epoch 1057 | Train loss 0.21973355114459991
Train Accuracy 89.42857142857143 | Test Accuracy 92.0
Epoch 1058 | Train loss 0.20548899471759796
Train Accuracy 89.28571428571429 | Test Accuracy 92.33333333333333
Epoch 1059 | Train loss 0.23809471726417542
Train Accuracy 89.14285714285714 | Test Accu

Train Accuracy 89.28571428571429 | Test Accuracy 93.0
Epoch 1131 | Train loss 0.2440585494041443
Train Accuracy 89.71428571428571 | Test Accuracy 92.33333333333333
Epoch 1132 | Train loss 0.21524961292743683
Train Accuracy 89.14285714285714 | Test Accuracy 92.33333333333333
Epoch 1133 | Train loss 0.17744359374046326
Train Accuracy 89.0 | Test Accuracy 93.0
Epoch 1134 | Train loss 0.3463570177555084
Train Accuracy 89.42857142857143 | Test Accuracy 92.0
Epoch 1135 | Train loss 0.295401394367218
Train Accuracy 88.85714285714286 | Test Accuracy 93.66666666666667
Epoch 1136 | Train loss 0.2818218767642975
Train Accuracy 88.57142857142857 | Test Accuracy 91.33333333333333
Epoch 1137 | Train loss 0.16426175832748413
Train Accuracy 89.0 | Test Accuracy 93.0
Epoch 1138 | Train loss 0.16119734942913055
Train Accuracy 89.28571428571429 | Test Accuracy 92.33333333333333
Epoch 1139 | Train loss 0.20064464211463928
Train Accuracy 89.28571428571429 | Test Accuracy 91.33333333333333
Epoch 1140 | Trai

Train Accuracy 89.28571428571429 | Test Accuracy 91.33333333333333
Epoch 1212 | Train loss 0.18680480122566223
Train Accuracy 89.0 | Test Accuracy 93.0
Epoch 1213 | Train loss 0.2641283869743347
Train Accuracy 89.14285714285714 | Test Accuracy 92.33333333333333
Epoch 1214 | Train loss 0.3874591290950775
Train Accuracy 89.57142857142857 | Test Accuracy 92.66666666666666
Epoch 1215 | Train loss 0.19160638749599457
Train Accuracy 89.28571428571429 | Test Accuracy 92.33333333333333
Epoch 1216 | Train loss 0.34755638241767883
Train Accuracy 89.14285714285714 | Test Accuracy 92.33333333333333
Epoch 1217 | Train loss 0.17039960622787476
Train Accuracy 89.14285714285714 | Test Accuracy 92.66666666666666
Epoch 1218 | Train loss 0.4305606782436371
Train Accuracy 89.71428571428571 | Test Accuracy 92.0
Epoch 1219 | Train loss 0.24810218811035156
Train Accuracy 89.14285714285714 | Test Accuracy 92.66666666666666
Epoch 1220 | Train loss 0.23630622029304504
Train Accuracy 89.14285714285714 | Test Acc

Epoch 1291 | Train loss 0.1854020059108734
Train Accuracy 89.57142857142857 | Test Accuracy 92.33333333333333
Epoch 1292 | Train loss 0.3054267168045044
Train Accuracy 88.85714285714286 | Test Accuracy 93.0
Epoch 1293 | Train loss 0.32452672719955444
Train Accuracy 89.42857142857143 | Test Accuracy 91.33333333333333
Epoch 1294 | Train loss 0.3365669846534729
Train Accuracy 89.71428571428571 | Test Accuracy 92.66666666666666
Epoch 1295 | Train loss 0.3579453229904175
Train Accuracy 89.28571428571429 | Test Accuracy 92.66666666666666
Epoch 1296 | Train loss 0.16974560916423798
Train Accuracy 88.85714285714286 | Test Accuracy 93.0
Epoch 1297 | Train loss 0.2727290093898773
Train Accuracy 89.28571428571429 | Test Accuracy 91.33333333333333
Epoch 1298 | Train loss 0.3196339011192322
Train Accuracy 89.57142857142857 | Test Accuracy 91.66666666666666
Epoch 1299 | Train loss 0.25009140372276306
Train Accuracy 88.85714285714286 | Test Accuracy 93.0
Epoch 1300 | Train loss 0.22062012553215027
Tr

Train Accuracy 88.85714285714286 | Test Accuracy 93.0
Epoch 1371 | Train loss 0.3060916066169739
Train Accuracy 89.14285714285714 | Test Accuracy 92.33333333333333
Epoch 1372 | Train loss 0.14128676056861877
Train Accuracy 89.28571428571429 | Test Accuracy 92.33333333333333
Epoch 1373 | Train loss 0.2285812795162201
Train Accuracy 89.14285714285714 | Test Accuracy 92.33333333333333
Epoch 1374 | Train loss 0.16944323480129242
Train Accuracy 89.28571428571429 | Test Accuracy 94.0
Epoch 1375 | Train loss 0.331825315952301
Train Accuracy 89.57142857142857 | Test Accuracy 91.33333333333333
Epoch 1376 | Train loss 0.16744069755077362
Train Accuracy 89.14285714285714 | Test Accuracy 92.33333333333333
Epoch 1377 | Train loss 0.45748382806777954
Train Accuracy 89.14285714285714 | Test Accuracy 93.0
Epoch 1378 | Train loss 0.1181030198931694
Train Accuracy 89.57142857142857 | Test Accuracy 91.33333333333333
Epoch 1379 | Train loss 0.18527691066265106
Train Accuracy 89.14285714285714 | Test Accur

Train Accuracy 89.0 | Test Accuracy 93.0
Epoch 1451 | Train loss 0.2941170632839203
Train Accuracy 89.28571428571429 | Test Accuracy 91.33333333333333
Epoch 1452 | Train loss 0.20109836757183075
Train Accuracy 89.14285714285714 | Test Accuracy 93.0
Epoch 1453 | Train loss 0.355629026889801
Train Accuracy 89.0 | Test Accuracy 92.33333333333333
Epoch 1454 | Train loss 0.26175656914711
Train Accuracy 89.14285714285714 | Test Accuracy 91.0
Epoch 1455 | Train loss 0.3219422996044159
Train Accuracy 88.85714285714286 | Test Accuracy 93.33333333333333
Epoch 1456 | Train loss 0.15709799528121948
Train Accuracy 89.28571428571429 | Test Accuracy 91.33333333333333
Epoch 1457 | Train loss 0.19896624982357025
Train Accuracy 89.28571428571429 | Test Accuracy 92.33333333333333
Epoch 1458 | Train loss 0.21227143704891205
Train Accuracy 89.28571428571429 | Test Accuracy 94.0
Epoch 1459 | Train loss 0.15579622983932495
Train Accuracy 89.14285714285714 | Test Accuracy 91.33333333333333
Epoch 1460 | Train 

Epoch 1532 | Train loss 0.30766910314559937
Train Accuracy 89.14285714285714 | Test Accuracy 94.0
Epoch 1533 | Train loss 0.19517752528190613
Train Accuracy 89.14285714285714 | Test Accuracy 91.0
Epoch 1534 | Train loss 0.11438057571649551
Train Accuracy 89.28571428571429 | Test Accuracy 93.66666666666667
Epoch 1535 | Train loss 0.19509553909301758
Train Accuracy 89.57142857142857 | Test Accuracy 92.66666666666666
Epoch 1536 | Train loss 0.1952371597290039
Train Accuracy 89.28571428571429 | Test Accuracy 92.33333333333333
Epoch 1537 | Train loss 0.3904685974121094
Train Accuracy 89.42857142857143 | Test Accuracy 94.0
Epoch 1538 | Train loss 0.21672460436820984
Train Accuracy 88.71428571428571 | Test Accuracy 91.33333333333333
Epoch 1539 | Train loss 0.17561960220336914
Train Accuracy 89.0 | Test Accuracy 92.33333333333333
Epoch 1540 | Train loss 0.19005876779556274
Train Accuracy 89.14285714285714 | Test Accuracy 93.66666666666667
Epoch 1541 | Train loss 0.3144333064556122
Train Accura

Train Accuracy 88.85714285714286 | Test Accuracy 93.0
Epoch 1612 | Train loss 0.19419579207897186
Train Accuracy 89.42857142857143 | Test Accuracy 92.33333333333333
Epoch 1613 | Train loss 0.22002199292182922
Train Accuracy 89.0 | Test Accuracy 93.0
Epoch 1614 | Train loss 0.22351999580860138
Train Accuracy 88.85714285714286 | Test Accuracy 93.0
Epoch 1615 | Train loss 0.44517457485198975
Train Accuracy 89.14285714285714 | Test Accuracy 91.0
Epoch 1616 | Train loss 0.2672085464000702
Train Accuracy 89.28571428571429 | Test Accuracy 94.0
Epoch 1617 | Train loss 0.1715114265680313
Train Accuracy 89.57142857142857 | Test Accuracy 91.33333333333333
Epoch 1618 | Train loss 0.1282842606306076
Train Accuracy 89.42857142857143 | Test Accuracy 92.33333333333333
Epoch 1619 | Train loss 0.20586930215358734
Train Accuracy 89.14285714285714 | Test Accuracy 93.66666666666667
Epoch 1620 | Train loss 0.18361811339855194
Train Accuracy 89.0 | Test Accuracy 92.33333333333333
Epoch 1621 | Train loss 0.23

Epoch 1693 | Train loss 0.2598377466201782
Train Accuracy 88.85714285714286 | Test Accuracy 92.66666666666666
Epoch 1694 | Train loss 0.3082003593444824
Train Accuracy 88.85714285714286 | Test Accuracy 92.66666666666666
Epoch 1695 | Train loss 0.15523187816143036
Train Accuracy 89.57142857142857 | Test Accuracy 91.33333333333333
Epoch 1696 | Train loss 0.17274118959903717
Train Accuracy 88.85714285714286 | Test Accuracy 93.0
Epoch 1697 | Train loss 0.3002180755138397
Train Accuracy 89.57142857142857 | Test Accuracy 91.33333333333333
Epoch 1698 | Train loss 0.33533814549446106
Train Accuracy 89.14285714285714 | Test Accuracy 92.33333333333333
Epoch 1699 | Train loss 0.27569904923439026
Train Accuracy 89.14285714285714 | Test Accuracy 92.66666666666666
Epoch 1700 | Train loss 0.26333382725715637
Train Accuracy 89.57142857142857 | Test Accuracy 92.0
Epoch 1701 | Train loss 0.2900731861591339
Train Accuracy 89.42857142857143 | Test Accuracy 94.0
Epoch 1702 | Train loss 0.3040015399456024
T

Train Accuracy 89.28571428571429 | Test Accuracy 93.33333333333333
Epoch 1772 | Train loss 0.27381423115730286
Train Accuracy 89.28571428571429 | Test Accuracy 93.0
Epoch 1773 | Train loss 0.3988724946975708
Train Accuracy 89.42857142857143 | Test Accuracy 91.33333333333333
Epoch 1774 | Train loss 0.1993563175201416
Train Accuracy 89.14285714285714 | Test Accuracy 92.66666666666666
Epoch 1775 | Train loss 0.32198336720466614
Train Accuracy 89.42857142857143 | Test Accuracy 91.33333333333333
Epoch 1776 | Train loss 0.22189736366271973
Train Accuracy 89.28571428571429 | Test Accuracy 93.33333333333333
Epoch 1777 | Train loss 0.2379465252161026
Train Accuracy 89.57142857142857 | Test Accuracy 91.66666666666666
Epoch 1778 | Train loss 0.2395857274532318
Train Accuracy 89.28571428571429 | Test Accuracy 93.33333333333333
Epoch 1779 | Train loss 0.17349085211753845
Train Accuracy 89.42857142857143 | Test Accuracy 91.33333333333333
Epoch 1780 | Train loss 0.3677123486995697
Train Accuracy 89.5

Train Accuracy 89.42857142857143 | Test Accuracy 91.33333333333333
Epoch 1850 | Train loss 0.2798391282558441
Train Accuracy 89.71428571428571 | Test Accuracy 92.66666666666666
Epoch 1851 | Train loss 0.13864842057228088
Train Accuracy 89.42857142857143 | Test Accuracy 91.0
Epoch 1852 | Train loss 0.23569051921367645
Train Accuracy 89.57142857142857 | Test Accuracy 91.66666666666666
Epoch 1853 | Train loss 0.16958440840244293
Train Accuracy 89.57142857142857 | Test Accuracy 91.0
Epoch 1854 | Train loss 0.21136029064655304
Train Accuracy 89.42857142857143 | Test Accuracy 92.33333333333333
Epoch 1855 | Train loss 0.34126681089401245
Train Accuracy 89.71428571428571 | Test Accuracy 91.0
Epoch 1856 | Train loss 0.3162936866283417
Train Accuracy 89.42857142857143 | Test Accuracy 92.33333333333333
Epoch 1857 | Train loss 0.21360333263874054
Train Accuracy 89.57142857142857 | Test Accuracy 91.33333333333333
Epoch 1858 | Train loss 0.2666623294353485
Train Accuracy 89.71428571428571 | Test Acc

Epoch 1929 | Train loss 0.39223018288612366
Train Accuracy 89.42857142857143 | Test Accuracy 93.0
Epoch 1930 | Train loss 0.18698886036872864
Train Accuracy 89.57142857142857 | Test Accuracy 91.66666666666666
Epoch 1931 | Train loss 0.34777122735977173
Train Accuracy 89.71428571428571 | Test Accuracy 91.33333333333333
Epoch 1932 | Train loss 0.16935913264751434
Train Accuracy 89.57142857142857 | Test Accuracy 91.66666666666666
Epoch 1933 | Train loss 0.28295639157295227
Train Accuracy 89.57142857142857 | Test Accuracy 91.66666666666666
Epoch 1934 | Train loss 0.20604726672172546
Train Accuracy 89.42857142857143 | Test Accuracy 93.0
Epoch 1935 | Train loss 0.31411460041999817
Train Accuracy 89.57142857142857 | Test Accuracy 92.0
Epoch 1936 | Train loss 0.2249450534582138
Train Accuracy 88.85714285714286 | Test Accuracy 92.66666666666666
Epoch 1937 | Train loss 0.21810446679592133
Train Accuracy 89.57142857142857 | Test Accuracy 92.0
Epoch 1938 | Train loss 0.22976845502853394
Train Accu

Train Accuracy 89.57142857142857 | Test Accuracy 92.33333333333333
Epoch 2008 | Train loss 0.38697198033332825
Train Accuracy 89.57142857142857 | Test Accuracy 92.33333333333333
Epoch 2009 | Train loss 0.2438514679670334
Train Accuracy 90.0 | Test Accuracy 91.33333333333333
Epoch 2010 | Train loss 0.2323634922504425
Train Accuracy 89.57142857142857 | Test Accuracy 93.0
Epoch 2011 | Train loss 0.4530963897705078
Train Accuracy 89.85714285714286 | Test Accuracy 91.66666666666666
Epoch 2012 | Train loss 0.1692916750907898
Train Accuracy 89.57142857142857 | Test Accuracy 92.33333333333333
Epoch 2013 | Train loss 0.1648891419172287
Train Accuracy 89.71428571428571 | Test Accuracy 92.33333333333333
Epoch 2014 | Train loss 0.31315523386001587
Train Accuracy 89.71428571428571 | Test Accuracy 92.66666666666666
Epoch 2015 | Train loss 0.41452133655548096
Train Accuracy 89.85714285714286 | Test Accuracy 91.66666666666666
Epoch 2016 | Train loss 0.2270694077014923
Train Accuracy 89.42857142857143 

Train Accuracy 89.71428571428571 | Test Accuracy 91.66666666666666
Epoch 2086 | Train loss 0.36273515224456787
Train Accuracy 89.57142857142857 | Test Accuracy 92.33333333333333
Epoch 2087 | Train loss 0.21941827237606049
Train Accuracy 89.71428571428571 | Test Accuracy 93.66666666666667
Epoch 2088 | Train loss 0.25030678510665894
Train Accuracy 89.57142857142857 | Test Accuracy 92.33333333333333
Epoch 2089 | Train loss 0.19321705400943756
Train Accuracy 89.57142857142857 | Test Accuracy 92.66666666666666
Epoch 2090 | Train loss 0.3081326484680176
Train Accuracy 89.71428571428571 | Test Accuracy 93.66666666666667
Epoch 2091 | Train loss 0.1649024784564972
Train Accuracy 89.57142857142857 | Test Accuracy 92.0
Epoch 2092 | Train loss 0.2615460157394409
Train Accuracy 89.85714285714286 | Test Accuracy 92.0
Epoch 2093 | Train loss 0.31896135210990906
Train Accuracy 89.57142857142857 | Test Accuracy 92.33333333333333
Epoch 2094 | Train loss 0.22818142175674438
Train Accuracy 89.571428571428

Epoch 2164 | Train loss 0.19956669211387634
Train Accuracy 89.85714285714286 | Test Accuracy 91.66666666666666
Epoch 2165 | Train loss 0.24752385914325714
Train Accuracy 89.57142857142857 | Test Accuracy 92.33333333333333
Epoch 2166 | Train loss 0.35262832045555115
Train Accuracy 89.57142857142857 | Test Accuracy 91.66666666666666
Epoch 2167 | Train loss 0.23820559680461884
Train Accuracy 89.42857142857143 | Test Accuracy 92.33333333333333
Epoch 2168 | Train loss 0.26910820603370667
Train Accuracy 89.71428571428571 | Test Accuracy 91.66666666666666
Epoch 2169 | Train loss 0.1128237396478653
Train Accuracy 89.57142857142857 | Test Accuracy 93.0
Epoch 2170 | Train loss 0.24331310391426086
Train Accuracy 89.71428571428571 | Test Accuracy 92.33333333333333
Epoch 2171 | Train loss 0.24829056859016418
Train Accuracy 89.71428571428571 | Test Accuracy 91.66666666666666
Epoch 2172 | Train loss 0.3988001048564911
Train Accuracy 89.14285714285714 | Test Accuracy 92.33333333333333
Epoch 2173 | Tra

Train Accuracy 89.57142857142857 | Test Accuracy 91.66666666666666
Epoch 2242 | Train loss 0.308430939912796
Train Accuracy 89.71428571428571 | Test Accuracy 92.33333333333333
Epoch 2243 | Train loss 0.12392867356538773
Train Accuracy 89.71428571428571 | Test Accuracy 91.66666666666666
Epoch 2244 | Train loss 0.27581092715263367
Train Accuracy 89.28571428571429 | Test Accuracy 92.66666666666666
Epoch 2245 | Train loss 0.36665135622024536
Train Accuracy 89.85714285714286 | Test Accuracy 91.66666666666666
Epoch 2246 | Train loss 0.1767943650484085
Train Accuracy 89.42857142857143 | Test Accuracy 92.66666666666666
Epoch 2247 | Train loss 0.3406369984149933
Train Accuracy 89.71428571428571 | Test Accuracy 91.66666666666666
Epoch 2248 | Train loss 0.1553032249212265
Train Accuracy 89.28571428571429 | Test Accuracy 92.33333333333333
Epoch 2249 | Train loss 0.3498297929763794
Train Accuracy 89.85714285714286 | Test Accuracy 91.66666666666666
Epoch 2250 | Train loss 0.2732314169406891
Train Ac

Epoch 2317 | Train loss 0.18584690988063812
Train Accuracy 89.71428571428571 | Test Accuracy 93.66666666666667
Epoch 2318 | Train loss 0.2690022885799408
Train Accuracy 89.57142857142857 | Test Accuracy 93.66666666666667
Epoch 2319 | Train loss 0.2679866552352905
Train Accuracy 89.71428571428571 | Test Accuracy 92.33333333333333
Epoch 2320 | Train loss 0.19006861746311188
Train Accuracy 89.71428571428571 | Test Accuracy 93.0
Epoch 2321 | Train loss 0.2324705272912979
Train Accuracy 89.57142857142857 | Test Accuracy 93.66666666666667
Epoch 2322 | Train loss 0.2996664345264435
Train Accuracy 89.71428571428571 | Test Accuracy 92.33333333333333
Epoch 2323 | Train loss 0.3187430500984192
Train Accuracy 89.42857142857143 | Test Accuracy 92.33333333333333
Epoch 2324 | Train loss 0.2926437556743622
Train Accuracy 89.71428571428571 | Test Accuracy 91.66666666666666
Epoch 2325 | Train loss 0.21880443394184113
Train Accuracy 89.57142857142857 | Test Accuracy 93.33333333333333
Epoch 2326 | Train l

Train Accuracy 89.57142857142857 | Test Accuracy 92.33333333333333
Epoch 2396 | Train loss 0.1493617445230484
Train Accuracy 89.71428571428571 | Test Accuracy 93.33333333333333
Epoch 2397 | Train loss 0.17339491844177246
Train Accuracy 89.57142857142857 | Test Accuracy 92.33333333333333
Epoch 2398 | Train loss 0.20098017156124115
Train Accuracy 89.57142857142857 | Test Accuracy 93.66666666666667
Epoch 2399 | Train loss 0.29462355375289917
Train Accuracy 89.57142857142857 | Test Accuracy 93.66666666666667
Epoch 2400 | Train loss 0.2224157303571701
Train Accuracy 89.57142857142857 | Test Accuracy 92.33333333333333
Epoch 2401 | Train loss 0.1628667414188385
Train Accuracy 89.85714285714286 | Test Accuracy 92.33333333333333
Epoch 2402 | Train loss 0.25500160455703735
Train Accuracy 89.42857142857143 | Test Accuracy 92.33333333333333
Epoch 2403 | Train loss 0.23992560803890228
Train Accuracy 89.85714285714286 | Test Accuracy 92.0
Epoch 2404 | Train loss 0.190111443400383
Train Accuracy 89.7

Train Accuracy 89.57142857142857 | Test Accuracy 91.33333333333333
Epoch 2473 | Train loss 0.14235448837280273
Train Accuracy 89.57142857142857 | Test Accuracy 92.33333333333333
Epoch 2474 | Train loss 0.19546569883823395
Train Accuracy 89.28571428571429 | Test Accuracy 91.66666666666666
Epoch 2475 | Train loss 0.24060018360614777
Train Accuracy 89.57142857142857 | Test Accuracy 92.33333333333333
Epoch 2476 | Train loss 0.24712806940078735
Train Accuracy 89.85714285714286 | Test Accuracy 91.66666666666666
Epoch 2477 | Train loss 0.14059050381183624
Train Accuracy 89.57142857142857 | Test Accuracy 92.33333333333333
Epoch 2478 | Train loss 0.29512864351272583
Train Accuracy 89.57142857142857 | Test Accuracy 93.33333333333333
Epoch 2479 | Train loss 0.2922733724117279
Train Accuracy 89.57142857142857 | Test Accuracy 92.0
Epoch 2480 | Train loss 0.23586271703243256
Train Accuracy 89.57142857142857 | Test Accuracy 93.66666666666667
Epoch 2481 | Train loss 0.16177457571029663
Train Accuracy 

Epoch 2549 | Train loss 0.1953885406255722
Train Accuracy 89.42857142857143 | Test Accuracy 92.33333333333333
Epoch 2550 | Train loss 0.22751589119434357
Train Accuracy 89.42857142857143 | Test Accuracy 92.33333333333333
Epoch 2551 | Train loss 0.30566543340682983
Train Accuracy 89.57142857142857 | Test Accuracy 93.66666666666667
Epoch 2552 | Train loss 0.19285911321640015
Train Accuracy 89.42857142857143 | Test Accuracy 92.33333333333333
Epoch 2553 | Train loss 0.3659786283969879
Train Accuracy 89.57142857142857 | Test Accuracy 92.33333333333333
Epoch 2554 | Train loss 0.2848609983921051
Train Accuracy 89.57142857142857 | Test Accuracy 92.33333333333333
Epoch 2555 | Train loss 0.20661847293376923
Train Accuracy 89.85714285714286 | Test Accuracy 91.66666666666666
Epoch 2556 | Train loss 0.16693121194839478
Train Accuracy 89.57142857142857 | Test Accuracy 93.33333333333333
Epoch 2557 | Train loss 0.24597342312335968
Train Accuracy 89.57142857142857 | Test Accuracy 92.33333333333333
Epoc

Train Accuracy 89.57142857142857 | Test Accuracy 92.33333333333333
Epoch 2625 | Train loss 0.29240038990974426
Train Accuracy 89.28571428571429 | Test Accuracy 91.66666666666666
Epoch 2626 | Train loss 0.16485358774662018
Train Accuracy 89.42857142857143 | Test Accuracy 93.0
Epoch 2627 | Train loss 0.2029821127653122
Train Accuracy 89.14285714285714 | Test Accuracy 92.33333333333333
Epoch 2628 | Train loss 0.32106125354766846
Train Accuracy 89.57142857142857 | Test Accuracy 93.0
Epoch 2629 | Train loss 0.27544400095939636
Train Accuracy 89.57142857142857 | Test Accuracy 92.33333333333333
Epoch 2630 | Train loss 0.3120211064815521
Train Accuracy 89.57142857142857 | Test Accuracy 93.66666666666667
Epoch 2631 | Train loss 0.1953354775905609
Train Accuracy 89.42857142857143 | Test Accuracy 93.0
Epoch 2632 | Train loss 0.26913124322891235
Train Accuracy 89.57142857142857 | Test Accuracy 93.66666666666667
Epoch 2633 | Train loss 0.23880355060100555
Train Accuracy 89.57142857142857 | Test Acc

Epoch 2700 | Train loss 0.18559475243091583
Train Accuracy 89.57142857142857 | Test Accuracy 93.66666666666667
Epoch 2701 | Train loss 0.20476922392845154
Train Accuracy 89.57142857142857 | Test Accuracy 93.33333333333333
Epoch 2702 | Train loss 0.2580026388168335
Train Accuracy 89.57142857142857 | Test Accuracy 93.66666666666667
Epoch 2703 | Train loss 0.13051737844944
Train Accuracy 89.14285714285714 | Test Accuracy 92.33333333333333
Epoch 2704 | Train loss 0.3093021810054779
Train Accuracy 89.14285714285714 | Test Accuracy 91.66666666666666
Epoch 2705 | Train loss 0.13984225690364838
Train Accuracy 89.14285714285714 | Test Accuracy 92.33333333333333
Epoch 2706 | Train loss 0.23759394884109497
Train Accuracy 89.57142857142857 | Test Accuracy 93.33333333333333
Epoch 2707 | Train loss 0.17616385221481323
Train Accuracy 89.0 | Test Accuracy 92.66666666666666
Epoch 2708 | Train loss 0.1776224970817566
Train Accuracy 90.0 | Test Accuracy 91.66666666666666
Epoch 2709 | Train loss 0.2652613

Train Accuracy 89.85714285714286 | Test Accuracy 91.66666666666666
Epoch 2776 | Train loss 0.21469418704509735
Train Accuracy 89.71428571428571 | Test Accuracy 92.0
Epoch 2777 | Train loss 0.18500562012195587
Train Accuracy 89.28571428571429 | Test Accuracy 91.66666666666666
Epoch 2778 | Train loss 0.22207340598106384
Train Accuracy 89.85714285714286 | Test Accuracy 92.33333333333333
Epoch 2779 | Train loss 0.27448228001594543
Train Accuracy 89.71428571428571 | Test Accuracy 92.66666666666666
Epoch 2780 | Train loss 0.17717161774635315
Train Accuracy 89.57142857142857 | Test Accuracy 93.66666666666667
Epoch 2781 | Train loss 0.19278855621814728
Train Accuracy 89.57142857142857 | Test Accuracy 93.66666666666667
Epoch 2782 | Train loss 0.1747628152370453
Train Accuracy 89.71428571428571 | Test Accuracy 93.33333333333333
Epoch 2783 | Train loss 0.19165681302547455
Train Accuracy 89.42857142857143 | Test Accuracy 92.33333333333333
Epoch 2784 | Train loss 0.19857816398143768
Train Accuracy 

KeyboardInterrupt: 

In [53]:
# sanity check

In [20]:
# let's try the double banana example
double_banana = nx.Graph()
double_banana.add_edge(0, 1)
double_banana.add_edge(0, 2)
double_banana.add_edge(0, 3)
double_banana.add_edge(0, 4)
double_banana.add_edge(1, 2)
double_banana.add_edge(1, 3)
double_banana.add_edge(1, 4)
double_banana.add_edge(2, 3)
double_banana.add_edge(2, 4)
double_banana.add_edge(7, 6)
double_banana.add_edge(7, 5)
double_banana.add_edge(7, 3)
double_banana.add_edge(7, 4)
double_banana.add_edge(6, 5)
double_banana.add_edge(6, 3)
double_banana.add_edge(6, 4)
double_banana.add_edge(5, 3)
double_banana.add_edge(5, 4)

In [21]:
graph_as_data = from_networkx(double_banana)
graph_as_data.x = generate_feature_vector(double_banana)
graph_as_data.label = 1

In [22]:
graph_as_data

Data(edge_index=[2, 36], num_nodes=8, x=[8, 1], label=1)

In [23]:
validation_set = DataLoader([graph_as_data], batch_size = 1, shuffle=True)

In [24]:
for batch in validation_set:
    pred = model(batch.x, batch.edge_index, batch.batch)
    print(pred[0])
    print(pred[1])

tensor([[0.9949]], grad_fn=<SigmoidBackward0>)
tensor([[5.2719]], grad_fn=<AddmmBackward0>)


In [25]:
train_acc, test_acc = check_accuracy(model, train_loader), check_accuracy(model, test_loader)
print(f"Train Accuracy {train_acc} | Test Accuracy {test_acc}")

Train Accuracy 89.0 | Test Accuracy 92.66666666666666


In [26]:
# generate statistics on the data

In [27]:
# play around with hyperparameters
    # hyper-opt: bayesian optimization
    # optimize learning rate
    # don't regularize 
# add non-minimally rigid graphs (test that hypothesis)

In [28]:
test_loader = DataLoader(test_data, batch_size = 1, shuffle=True)

In [29]:
wrong_examples = []

for batch in test_loader:
    pred, embedding = model(batch.x, batch.edge_index, batch.batch)
    pred = torch.squeeze(pred)
    y = batch.label
    predictions = (pred > 0.5).long() 
        
    if predictions != y:
        
        # iterate through the graph and remove edges
#         sample_graph = to_networkx(batch.x, to_undirected = True)
#         for (u, v) in sample_graph.edges:
#             print(u, " " , v)
        
        print(pred)
        print(batch.label)
        wrong_examples.append(batch)
        print("added bad example")
#     print((predictions == y))

tensor(0.2339, grad_fn=<SqueezeBackward0>)
tensor([1])
added bad example
tensor(0.6145, grad_fn=<SqueezeBackward0>)
tensor([0])
added bad example
tensor(0.4091, grad_fn=<SqueezeBackward0>)
tensor([1])
added bad example
tensor(0.1843, grad_fn=<SqueezeBackward0>)
tensor([1])
added bad example
tensor(0.5607, grad_fn=<SqueezeBackward0>)
tensor([0])
added bad example
tensor(0.1565, grad_fn=<SqueezeBackward0>)
tensor([1])
added bad example
tensor(0.5469, grad_fn=<SqueezeBackward0>)
tensor([0])
added bad example
tensor(0.7458, grad_fn=<SqueezeBackward0>)
tensor([0])
added bad example
tensor(0.8266, grad_fn=<SqueezeBackward0>)
tensor([0])
added bad example
tensor(0.5637, grad_fn=<SqueezeBackward0>)
tensor([0])
added bad example
tensor(0.5502, grad_fn=<SqueezeBackward0>)
tensor([0])
added bad example
tensor(0.0386, grad_fn=<SqueezeBackward0>)
tensor([1])
added bad example
tensor(0.8412, grad_fn=<SqueezeBackward0>)
tensor([0])
added bad example
tensor(0.4472, grad_fn=<SqueezeBackward0>)
tensor([

In [30]:
class LamanValidationDataset(InMemoryDataset):
    def __init__(self, root, data_dir, transform=None, pre_transform=None, pre_filter=None):
        self.data_dir = data_dir
        super().__init__(root, transform, pre_transform, pre_filter)
        self.data, self.slices = torch.load(self.processed_paths[0])
        
    @property
    def processed_file_names(self):
        return ['data_validation.pt']
        
    def process(self):
        # processing code here
        total_laman_data = None
        with gzip.open(self.data_dir, 'r') as f:
            total_laman_data = pickle.load(f)
            
        print(self.data_dir)
        print(len(total_laman_data))
        data_list = []
        ind = 0
        # convert from graph to Data object
        for graph in total_laman_data[0]:
            ind += 1
            num_nodes = nx.number_of_nodes(graph)
            x = generate_feature_vector(graph)
            graph_as_data = from_networkx(graph)
            graph_as_data.x = x
            graph_as_data.label = 0
            data_list.append(graph_as_data)
            
        ind = 0
        for graph in total_laman_data[1]:
            ind += 1
            num_nodes = nx.number_of_nodes(graph)
            x = generate_feature_vector(graph)
            graph_as_data = from_networkx(graph)
            graph_as_data.x = x
            graph_as_data.label = 1
            data_list.append(graph_as_data)
            
        for graph in total_laman_data[2]:
            ind += 1
            num_nodes = nx.number_of_nodes(graph)
            x = generate_feature_vector(graph)
            graph_as_data = from_networkx(graph)
            graph_as_data.x = x
            graph_as_data.label = 2
            data_list.append(graph_as_data)
            
        data, slices = self.collate(data_list)
        torch.save((data, slices), self.processed_paths[0])

In [31]:
DATA_VALIDATION_PATH = "data/broken.pkl.gz"

In [32]:
laman_data = LamanValidationDataset("", DATA_VALIDATION_PATH)

In [33]:
validation_loader = DataLoader(laman_data, batch_size = 1, shuffle=True)

In [34]:
wrong_examples = []

for batch in validation_loader:
    pred, embedding = model(batch.x, batch.edge_index, batch.batch)
    pred = torch.squeeze(pred)
    y = batch.label
    predictions = (pred > 0.5).long() 
        
    if predictions != y:
        
        # iterate through the graph and remove edges
#         sample_graph = to_networkx(batch.x[0], to_undirected = True)
#         for (u, v) in sample_graph.edges:
#             print(u, " " , v)
        
        print(pred)
        print(batch.label)
        wrong_examples.append(batch)
        print("added bad example")
#     print((predictions == y))

tensor(0.0970, grad_fn=<SqueezeBackward0>)
tensor([1])
added bad example
tensor(0.3866, grad_fn=<SqueezeBackward0>)
tensor([1])
added bad example
tensor(0.6340, grad_fn=<SqueezeBackward0>)
tensor([0])
added bad example
tensor(0.6810, grad_fn=<SqueezeBackward0>)
tensor([0])
added bad example
tensor(0.5220, grad_fn=<SqueezeBackward0>)
tensor([0])
added bad example
tensor(0.3963, grad_fn=<SqueezeBackward0>)
tensor([1])
added bad example
tensor(0.7057, grad_fn=<SqueezeBackward0>)
tensor([0])
added bad example
tensor(0.1699, grad_fn=<SqueezeBackward0>)
tensor([2])
added bad example
tensor(0.6467, grad_fn=<SqueezeBackward0>)
tensor([0])
added bad example
tensor(0.0689, grad_fn=<SqueezeBackward0>)
tensor([1])
added bad example
tensor(0.9106, grad_fn=<SqueezeBackward0>)
tensor([0])
added bad example
tensor(0.6678, grad_fn=<SqueezeBackward0>)
tensor([0])
added bad example
tensor(0.4053, grad_fn=<SqueezeBackward0>)
tensor([1])
added bad example
tensor(0.0630, grad_fn=<SqueezeBackward0>)
tensor([